//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnKeyBrokerSignUp.WebUI.TradingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Affiliate", Namespace="https://www.tradereporting.com/")]
    [System.SerializableAttribute()]
    public partial class Affiliate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AffiliateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AffiliateID {
            get {
                return this.AffiliateIDField;
            }
            set {
                if ((this.AffiliateIDField.Equals(value) != true)) {
                    this.AffiliateIDField = value;
                    this.RaisePropertyChanged("AffiliateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AffiliateAccount", Namespace="https://www.tradereporting.com/")]
    [System.SerializableAttribute()]
    public partial class AffiliateAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.tradereporting.com/", ConfigurationName="TradingService.TRServiceSoap")]
    public interface TRServiceSoap {
        
        // CODEGEN: Generating message contract since element name userid from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRLogin", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginResponse TRLogin(TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRAccountExist", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistResponse TRAccountExist(TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TROpenAccount", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountResponse TROpenAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TROpenAccountAffiliate", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateResponse TROpenAccountAffiliate(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRAddAccountAffiliate", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateResponse TRAddAccountAffiliate(TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRGameList", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListResponse TRGameList(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRGameListAccount", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountResponse TRGameListAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRGameAddAccount", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountResponse TRGameAddAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRGameDeleteAccount", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountResponse TRGameDeleteAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRCalculateCommission", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionResponse TRCalculateCommission(TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRCashJournal", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalResponse TRCashJournal(TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequest request);
        
        // CODEGEN: Generating message contract since element name stoken from namespace https://www.tradereporting.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.tradereporting.com/TRChangePassword", ReplyAction="*")]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordResponse TRChangePassword(TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRLogin", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequestBody Body;
        
        public TRLoginRequest() {
        }
        
        public TRLoginRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        public TRLoginRequestBody() {
        }
        
        public TRLoginRequestBody(string userid, string passwd) {
            this.userid = userid;
            this.passwd = passwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRLoginResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginResponseBody Body;
        
        public TRLoginResponse() {
        }
        
        public TRLoginResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRLoginResult;
        
        public TRLoginResponseBody() {
        }
        
        public TRLoginResponseBody(string TRLoginResult) {
            this.TRLoginResult = TRLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRAccountExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRAccountExist", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequestBody Body;
        
        public TRAccountExistRequest() {
        }
        
        public TRAccountExistRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRAccountExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subaccount;
        
        public TRAccountExistRequestBody() {
        }
        
        public TRAccountExistRequestBody(string stoken, string subaccount) {
            this.stoken = stoken;
            this.subaccount = subaccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRAccountExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRAccountExistResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistResponseBody Body;
        
        public TRAccountExistResponse() {
        }
        
        public TRAccountExistResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRAccountExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TRAccountExistResult;
        
        public TRAccountExistResponseBody() {
        }
        
        public TRAccountExistResponseBody(int TRAccountExistResult) {
            this.TRAccountExistResult = TRAccountExistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TROpenAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TROpenAccount", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequestBody Body;
        
        public TROpenAccountRequest() {
        }
        
        public TROpenAccountRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TROpenAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subaccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acctname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string addr3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string zip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string phone1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string phone2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string passwd;
        
        public TROpenAccountRequestBody() {
        }
        
        public TROpenAccountRequestBody(string stoken, string subaccount, string acctname, string addr1, string addr2, string addr3, string city, string state, string zip, string country, string phone1, string phone2, string email, string passwd) {
            this.stoken = stoken;
            this.subaccount = subaccount;
            this.acctname = acctname;
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.addr3 = addr3;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.country = country;
            this.phone1 = phone1;
            this.phone2 = phone2;
            this.email = email;
            this.passwd = passwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TROpenAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TROpenAccountResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountResponseBody Body;
        
        public TROpenAccountResponse() {
        }
        
        public TROpenAccountResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TROpenAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TROpenAccountResult;
        
        public TROpenAccountResponseBody() {
        }
        
        public TROpenAccountResponseBody(string TROpenAccountResult) {
            this.TROpenAccountResult = TROpenAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TROpenAccountAffiliateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TROpenAccountAffiliate", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequestBody Body;
        
        public TROpenAccountAffiliateRequest() {
        }
        
        public TROpenAccountAffiliateRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TROpenAccountAffiliateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subaccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string acctname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string addr3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string zip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string phone1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string phone2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string passwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string affiliatename;
        
        public TROpenAccountAffiliateRequestBody() {
        }
        
        public TROpenAccountAffiliateRequestBody(string stoken, string subaccount, string acctname, string addr1, string addr2, string addr3, string city, string state, string zip, string country, string phone1, string phone2, string email, string passwd, string affiliatename) {
            this.stoken = stoken;
            this.subaccount = subaccount;
            this.acctname = acctname;
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.addr3 = addr3;
            this.city = city;
            this.state = state;
            this.zip = zip;
            this.country = country;
            this.phone1 = phone1;
            this.phone2 = phone2;
            this.email = email;
            this.passwd = passwd;
            this.affiliatename = affiliatename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TROpenAccountAffiliateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TROpenAccountAffiliateResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateResponseBody Body;
        
        public TROpenAccountAffiliateResponse() {
        }
        
        public TROpenAccountAffiliateResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TROpenAccountAffiliateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TROpenAccountAffiliateResult;
        
        public TROpenAccountAffiliateResponseBody() {
        }
        
        public TROpenAccountAffiliateResponseBody(string TROpenAccountAffiliateResult) {
            this.TROpenAccountAffiliateResult = TROpenAccountAffiliateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRAddAccountAffiliateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRAddAccountAffiliate", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequestBody Body;
        
        public TRAddAccountAffiliateRequest() {
        }
        
        public TRAddAccountAffiliateRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRAddAccountAffiliateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subaccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string affiliatename;
        
        public TRAddAccountAffiliateRequestBody() {
        }
        
        public TRAddAccountAffiliateRequestBody(string stoken, string subaccount, string affiliatename) {
            this.stoken = stoken;
            this.subaccount = subaccount;
            this.affiliatename = affiliatename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRAddAccountAffiliateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRAddAccountAffiliateResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateResponseBody Body;
        
        public TRAddAccountAffiliateResponse() {
        }
        
        public TRAddAccountAffiliateResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRAddAccountAffiliateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRAddAccountAffiliateResult;
        
        public TRAddAccountAffiliateResponseBody() {
        }
        
        public TRAddAccountAffiliateResponseBody(string TRAddAccountAffiliateResult) {
            this.TRAddAccountAffiliateResult = TRAddAccountAffiliateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameList", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequestBody Body;
        
        public TRGameListRequest() {
        }
        
        public TRGameListRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        public TRGameListRequestBody() {
        }
        
        public TRGameListRequestBody(string stoken) {
            this.stoken = stoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameListResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListResponseBody Body;
        
        public TRGameListResponse() {
        }
        
        public TRGameListResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.Affiliate[] TRGameListResult;
        
        public TRGameListResponseBody() {
        }
        
        public TRGameListResponseBody(TurnKeyBrokerSignUp.WebUI.TradingService.Affiliate[] TRGameListResult) {
            this.TRGameListResult = TRGameListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameListAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameListAccount", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequestBody Body;
        
        public TRGameListAccountRequest() {
        }
        
        public TRGameListAccountRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameListAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int affid;
        
        public TRGameListAccountRequestBody() {
        }
        
        public TRGameListAccountRequestBody(string stoken, int affid) {
            this.stoken = stoken;
            this.affid = affid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameListAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameListAccountResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountResponseBody Body;
        
        public TRGameListAccountResponse() {
        }
        
        public TRGameListAccountResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameListAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.AffiliateAccount[] TRGameListAccountResult;
        
        public TRGameListAccountResponseBody() {
        }
        
        public TRGameListAccountResponseBody(TurnKeyBrokerSignUp.WebUI.TradingService.AffiliateAccount[] TRGameListAccountResult) {
            this.TRGameListAccountResult = TRGameListAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameAddAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameAddAccount", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequestBody Body;
        
        public TRGameAddAccountRequest() {
        }
        
        public TRGameAddAccountRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameAddAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int affid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sacct;
        
        public TRGameAddAccountRequestBody() {
        }
        
        public TRGameAddAccountRequestBody(string stoken, int affid, string sacct) {
            this.stoken = stoken;
            this.affid = affid;
            this.sacct = sacct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameAddAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameAddAccountResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountResponseBody Body;
        
        public TRGameAddAccountResponse() {
        }
        
        public TRGameAddAccountResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameAddAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRGameAddAccountResult;
        
        public TRGameAddAccountResponseBody() {
        }
        
        public TRGameAddAccountResponseBody(string TRGameAddAccountResult) {
            this.TRGameAddAccountResult = TRGameAddAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameDeleteAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameDeleteAccount", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequestBody Body;
        
        public TRGameDeleteAccountRequest() {
        }
        
        public TRGameDeleteAccountRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameDeleteAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int affid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sacct;
        
        public TRGameDeleteAccountRequestBody() {
        }
        
        public TRGameDeleteAccountRequestBody(string stoken, int affid, string sacct) {
            this.stoken = stoken;
            this.affid = affid;
            this.sacct = sacct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRGameDeleteAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRGameDeleteAccountResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountResponseBody Body;
        
        public TRGameDeleteAccountResponse() {
        }
        
        public TRGameDeleteAccountResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRGameDeleteAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRGameDeleteAccountResult;
        
        public TRGameDeleteAccountResponseBody() {
        }
        
        public TRGameDeleteAccountResponseBody(string TRGameDeleteAccountResult) {
            this.TRGameDeleteAccountResult = TRGameDeleteAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRCalculateCommissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRCalculateCommission", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequestBody Body;
        
        public TRCalculateCommissionRequest() {
        }
        
        public TRCalculateCommissionRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRCalculateCommissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subaccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string symbol;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string liquidityflag;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public float originalcommission;
        
        public TRCalculateCommissionRequestBody() {
        }
        
        public TRCalculateCommissionRequestBody(string stoken, string subaccount, string symbol, float qty, float price, string dest, string liquidityflag, float originalcommission) {
            this.stoken = stoken;
            this.subaccount = subaccount;
            this.symbol = symbol;
            this.qty = qty;
            this.price = price;
            this.dest = dest;
            this.liquidityflag = liquidityflag;
            this.originalcommission = originalcommission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRCalculateCommissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRCalculateCommissionResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionResponseBody Body;
        
        public TRCalculateCommissionResponse() {
        }
        
        public TRCalculateCommissionResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRCalculateCommissionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double TRCalculateCommissionResult;
        
        public TRCalculateCommissionResponseBody() {
        }
        
        public TRCalculateCommissionResponseBody(double TRCalculateCommissionResult) {
            this.TRCalculateCommissionResult = TRCalculateCommissionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRCashJournalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRCashJournal", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequestBody Body;
        
        public TRCashJournalRequest() {
        }
        
        public TRCashJournalRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRCashJournalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sacct;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string edate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string curr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string stype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string snote;
        
        public TRCashJournalRequestBody() {
        }
        
        public TRCashJournalRequestBody(string stoken, string sacct, string edate, string curr1, double amount, string stype, string snote) {
            this.stoken = stoken;
            this.sacct = sacct;
            this.edate = edate;
            this.curr1 = curr1;
            this.amount = amount;
            this.stype = stype;
            this.snote = snote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRCashJournalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRCashJournalResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalResponseBody Body;
        
        public TRCashJournalResponse() {
        }
        
        public TRCashJournalResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRCashJournalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRCashJournalResult;
        
        public TRCashJournalResponseBody() {
        }
        
        public TRCashJournalResponseBody(string TRCashJournalResult) {
            this.TRCashJournalResult = TRCashJournalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRChangePassword", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequestBody Body;
        
        public TRChangePasswordRequest() {
        }
        
        public TRChangePasswordRequest(TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subaccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string passwd;
        
        public TRChangePasswordRequestBody() {
        }
        
        public TRChangePasswordRequestBody(string stoken, string subaccount, string loginid, string passwd) {
            this.stoken = stoken;
            this.subaccount = subaccount;
            this.loginid = loginid;
            this.passwd = passwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TRChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TRChangePasswordResponse", Namespace="https://www.tradereporting.com/", Order=0)]
        public TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordResponseBody Body;
        
        public TRChangePasswordResponse() {
        }
        
        public TRChangePasswordResponse(TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.tradereporting.com/")]
    public partial class TRChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TRChangePasswordResult;
        
        public TRChangePasswordResponseBody() {
        }
        
        public TRChangePasswordResponseBody(string TRChangePasswordResult) {
            this.TRChangePasswordResult = TRChangePasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TRServiceSoapChannel : TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TRServiceSoapClient : System.ServiceModel.ClientBase<TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap>, TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap {
        
        public TRServiceSoapClient() {
        }
        
        public TRServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TRServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TRServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TRServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRLogin(TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequest request) {
            return base.Channel.TRLogin(request);
        }
        
        public string TRLogin(string userid, string passwd) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.passwd = passwd;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRLoginResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRLogin(inValue);
            return retVal.Body.TRLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRAccountExist(TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequest request) {
            return base.Channel.TRAccountExist(request);
        }
        
        public int TRAccountExist(string stoken, string subaccount) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.subaccount = subaccount;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRAccountExistResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRAccountExist(inValue);
            return retVal.Body.TRAccountExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TROpenAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequest request) {
            return base.Channel.TROpenAccount(request);
        }
        
        public string TROpenAccount(string stoken, string subaccount, string acctname, string addr1, string addr2, string addr3, string city, string state, string zip, string country, string phone1, string phone2, string email, string passwd) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.subaccount = subaccount;
            inValue.Body.acctname = acctname;
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.addr3 = addr3;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip = zip;
            inValue.Body.country = country;
            inValue.Body.phone1 = phone1;
            inValue.Body.phone2 = phone2;
            inValue.Body.email = email;
            inValue.Body.passwd = passwd;
            TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TROpenAccount(inValue);
            return retVal.Body.TROpenAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TROpenAccountAffiliate(TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequest request) {
            return base.Channel.TROpenAccountAffiliate(request);
        }
        
        public string TROpenAccountAffiliate(string stoken, string subaccount, string acctname, string addr1, string addr2, string addr3, string city, string state, string zip, string country, string phone1, string phone2, string email, string passwd, string affiliatename) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.subaccount = subaccount;
            inValue.Body.acctname = acctname;
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.addr3 = addr3;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip = zip;
            inValue.Body.country = country;
            inValue.Body.phone1 = phone1;
            inValue.Body.phone2 = phone2;
            inValue.Body.email = email;
            inValue.Body.passwd = passwd;
            inValue.Body.affiliatename = affiliatename;
            TurnKeyBrokerSignUp.WebUI.TradingService.TROpenAccountAffiliateResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TROpenAccountAffiliate(inValue);
            return retVal.Body.TROpenAccountAffiliateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRAddAccountAffiliate(TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequest request) {
            return base.Channel.TRAddAccountAffiliate(request);
        }
        
        public string TRAddAccountAffiliate(string stoken, string subaccount, string affiliatename) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.subaccount = subaccount;
            inValue.Body.affiliatename = affiliatename;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRAddAccountAffiliateResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRAddAccountAffiliate(inValue);
            return retVal.Body.TRAddAccountAffiliateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRGameList(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequest request) {
            return base.Channel.TRGameList(request);
        }
        
        public TurnKeyBrokerSignUp.WebUI.TradingService.Affiliate[] TRGameList(string stoken) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListRequestBody();
            inValue.Body.stoken = stoken;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRGameList(inValue);
            return retVal.Body.TRGameListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRGameListAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequest request) {
            return base.Channel.TRGameListAccount(request);
        }
        
        public TurnKeyBrokerSignUp.WebUI.TradingService.AffiliateAccount[] TRGameListAccount(string stoken, int affid) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.affid = affid;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameListAccountResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRGameListAccount(inValue);
            return retVal.Body.TRGameListAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRGameAddAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequest request) {
            return base.Channel.TRGameAddAccount(request);
        }
        
        public string TRGameAddAccount(string stoken, int affid, string sacct) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.affid = affid;
            inValue.Body.sacct = sacct;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameAddAccountResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRGameAddAccount(inValue);
            return retVal.Body.TRGameAddAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRGameDeleteAccount(TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequest request) {
            return base.Channel.TRGameDeleteAccount(request);
        }
        
        public string TRGameDeleteAccount(string stoken, int affid, string sacct) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.affid = affid;
            inValue.Body.sacct = sacct;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRGameDeleteAccountResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRGameDeleteAccount(inValue);
            return retVal.Body.TRGameDeleteAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRCalculateCommission(TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequest request) {
            return base.Channel.TRCalculateCommission(request);
        }
        
        public double TRCalculateCommission(string stoken, string subaccount, string symbol, float qty, float price, string dest, string liquidityflag, float originalcommission) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.subaccount = subaccount;
            inValue.Body.symbol = symbol;
            inValue.Body.qty = qty;
            inValue.Body.price = price;
            inValue.Body.dest = dest;
            inValue.Body.liquidityflag = liquidityflag;
            inValue.Body.originalcommission = originalcommission;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRCalculateCommissionResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRCalculateCommission(inValue);
            return retVal.Body.TRCalculateCommissionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRCashJournal(TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequest request) {
            return base.Channel.TRCashJournal(request);
        }
        
        public string TRCashJournal(string stoken, string sacct, string edate, string curr1, double amount, string stype, string snote) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.sacct = sacct;
            inValue.Body.edate = edate;
            inValue.Body.curr1 = curr1;
            inValue.Body.amount = amount;
            inValue.Body.stype = stype;
            inValue.Body.snote = snote;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRCashJournalResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRCashJournal(inValue);
            return retVal.Body.TRCashJournalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordResponse TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap.TRChangePassword(TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequest request) {
            return base.Channel.TRChangePassword(request);
        }
        
        public string TRChangePassword(string stoken, string subaccount, string loginid, string passwd) {
            TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequest inValue = new TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequest();
            inValue.Body = new TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordRequestBody();
            inValue.Body.stoken = stoken;
            inValue.Body.subaccount = subaccount;
            inValue.Body.loginid = loginid;
            inValue.Body.passwd = passwd;
            TurnKeyBrokerSignUp.WebUI.TradingService.TRChangePasswordResponse retVal = ((TurnKeyBrokerSignUp.WebUI.TradingService.TRServiceSoap)(this)).TRChangePassword(inValue);
            return retVal.Body.TRChangePasswordResult;
        }
    }
}
